Holo-Host/holo-nixpkgs

- README.md
@gavinrogers here's a PR on the latest change but you can review the whole thing of course
@neonphog @artbrock if you can also review the README.md language and confirm you are comfortable with it, or I can make the changes needed
> merging readme files

- modules/base.nix
- scripts/holoport-preflight.sh
> Ensure that network.target is up, so we can get the Ethernet MAC

- README.md
- ci.nix
- release.nix
See #50. This change makes Holo Nixpkgs CI much, much more responsive.
> holoportos-installers: remove from CI

- jobsets.nix
- profiles/hydra/master/specs/holo-nixpkgs.json
This reverts commit 2044e4415e126112b38b0941915537f3c92e4e1e.
> Revert "jobsets: disable polling", see #72

- jobsets.nix
> jobsets: fix remote pull requests

- overlays/holo-nixpkgs/build-dna/default.nix
- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/hclient/default.nix
- overlays/holo-nixpkgs/holofuel-app/default.nix
> npmToNix: bump to 6d2cbbc9d58566513019ae176bab7c2aeb68efae

- profiles/holoportos/qemu/default.nix
- shell.nix
> profiles/holoportos/qemu: improvements

- profiles/hydra/default.nix
> profiles/hydra: use UTC timezone

- profiles/hydra/default.nix
Allows @samrose to connect to Hydra master and minion services as superuser.
> profiles/hydra: allow superuser access to Sam Rose

- overlays/holo-nixpkgs/default.nix
- profiles/hydra/master/default.nix
See: https://quickstart.holo.host
> Host quickstart.holo.host

- profiles/hydra/master/default.nix
> profiles/hydra/master: vhosts for static files from holo-nixpkgs

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/wrangler/default.nix
> wrangler: init

- jobsets.nix
Staging is not being used so far and we'll restore it if we ever need it.
> jobsets: drop staging

- modules/services/holo-auth-client.nix
- modules/services/hp-admin-crypto-server.nix
- profiles/hardware/qemu/default.nix
Rebased alternative to #223 with addressed feedback.
> treewide: correct systemd service ordering

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/hydra/secure-github.diff
> hydra: do not store secret in Nix store

- profiles/holoportos/demo/default.nix
> profiles/targets/demo: add SSH key for PJ Klimek

- CONTRIBUTING.md
It's still quite a bit out of date and incomplete.
> CONTRIBUTING: update

- modules/default.nix
- modules/system/holo-nixpkgs/auto-upgrade.nix
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
- profiles/logical/hydra/default.nix
> system.holoportos.autoUpgrade -> system.holo-nixpkgs.autoUpgrade

- profiles/logical/holo/sim2h/default.nix
> logical/holo/sim2h: grant root access to Eric

- nixpkgs/src/default.nix
- nixpkgs/src/zerotier-1.4.6.patch
- profiles/physical/hpos/default.nix
This is a workaround for the issue that has been plaguing us for all this time that caused VMs to have poor ZeroTier connectivity.
cc @alastairong @pjkundert
> Fix ZeroTier connectivity issue

- overlays/holo-nixpkgs/dna-packages/default.nix
- overlays/holo-nixpkgs/holochain-rust/default.nix
> Updating holochain to v0.0.42 alpha5

- overlays/holo-nixpkgs/hpos-admin/default.nix
- overlays/holo-nixpkgs/hpos-admin/hpos-admin.py
- profiles/logical/holo/hydra/master/specs/hydra-example.json
> hpos-admin: fix /api/v1/status endpoint

- overlays/holo-nixpkgs/hpos-admin/hpos-admin.py
- tests/hpos-admin/default.nix
Pairing with @peeech an attempt to see if specific permission setting will succeed on hydra PR build
> 2020 02 05 hpos admin users group permissions

- overlays/holo-nixpkgs/default.nix
> nginxStable: apply application/wasm MIME patch instead of nginx

- modules/services/hpos-admin.nix
- profiles/logical/hpos/default.nix
- tests/hpos-admin/default.nix
Resolves #366. Not tested yet.
> modules/services/hpos-admin: create hpos-admin-users group

- overlays/holo-nixpkgs/dna-packages/default.nix
- profiles/logical/hpos/default.nix
- tests/holochain-conductor/default.nix
Removes communities dna from HPOS self hosted context.
> dnaPackages.holo-communities-dna: remove

- overlays/holo-nixpkgs/dna-packages/default.nix
Test PR for checking if sim2h communication works between DNS once they all use same sim2h server.
> Revert all DNAs to the ones using generic sim2h_url

- overlays/holo-nixpkgs/hpos-admin/hpos-admin.py
If we want to log anything else, let me know.
> hpos-admin: log CAS mismatches, resolves #388

- profiles/logical/holo/hydra/master/specs/holo-envoy.json
Adding holo-envoy project to hydra with jobsets and spec file
> profiles/logical/holo/hydra/master/specs: holo-envoy

- .github/CODEOWNERS
- .github/settings.yml
- profiles/logical/holo/default.nix
- profiles/logical/hpos/staged/default.nix
> treewide: update authorized users in holo-nixpkgs

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/dna-packages/default.nix
- profiles/logical/hpos/default.nix
Bumped to holofuel `v0.20.1-alpha1`
> dnaPackages.holofuel: Update DNA hashspace

- modules/services/holochain-conductor.nix
- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/dna-packages/default.nix
- profiles/logical/hpos/default.nix
Implements Holo-Host/rfcs#36.
Service code: https://github.com/Holo-Host/holo-update-conductor-config.
All names are subject to change :slightly_smiling_face:
> holochain-conductor: implement config merging

- overlays/holo-nixpkgs/default.nix
- profiles/logical/hpos/default.nix
> bump updater to rev 4102905

- modules/default.nix
- modules/services/automount.nix
- modules/system/holo-nixpkgs/usb-reset.nix
- overlays/holo-nixpkgs/default.nix
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
- profiles/physical/hpos/automount.nix
- profiles/physical/hpos/holoport-nano/default.nix
- profiles/physical/hpos/holoport-plus/default.nix
- profiles/physical/hpos/holoport/default.nix
This PR is cherry picking commits from #440 and applies to master, therefore creates no merge conflicts. Read for testing.
> USB Holoport reset on master

- .github/CODEOWNERS
- .github/settings.yml
- jobsets.nix
- profiles/logical/holo/hydra/master/default.nix
- shell.nix
This PR will:
- update Hydra settings so that it can run on 16GB RAM droplet of DO
- create protected branch `hydra` that Hydra will be serving to itself as a channel
> New Hydra setup

- profiles/logical/holo/repoxplorer/default.nix
Adding a new profile that defines our repoxplorer.
> profiles/repoxplorer: init

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/dna-packages/default.nix
- overlays/holo-nixpkgs/holochain-rust/default.nix
- profiles/logical/hpos/README.md
- profiles/logical/hpos/default.nix
> staging candidate 

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/hpos-update/default.nix
- overlays/holo-nixpkgs/hpos-update/hpos-update.sh
- profiles/logical/hpos/default.nix
This script is for making testing easier by simpler channel switching and update success feedback
> Add hpos-update script for testers

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/dna-packages/default.nix
- overlays/holo-nixpkgs/holochain-rust/default.nix
- tests/hpos-admin/default.nix
> [QA Staging]: UI enhancements

- overlays/holo-nixpkgs/dna-packages/default.nix
DNA Version: `0.21.4-alpha7`
DNA Hash: `Qme24JDDozSSNKNErp6yGt7qw4vdaX5xJKrmnLjRSJxnYC`
> [Staging]: New hash space

- overlays/holo-nixpkgs/dna-packages/default.nix
- overlays/holo-nixpkgs/holochain-rust/default.nix
DNA hash: `QmcKh6ffZ6178MVU8raPVp5GPD2Qm7t4pSpQrMnGPvKtdZ`
> [Staging]: mismatch hotfix

- modules/default.nix
- modules/services/holo-envoy.nix
- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/dna-packages/default.nix
- overlays/holo-nixpkgs/holo-envoy/default.nix
- overlays/holo-nixpkgs/holochain-rust/default.nix
- profiles/logical/hpos/default.nix
- release.nix
This is the work that was dev tested on #575
> holo-hosting release 

- modules/default.nix
- modules/profiles/README.md
- modules/profiles/development.nix
- modules/services/holo-router-agent.nix
- modules/services/holochain-conductor.nix
- modules/services/holochain.nix
- modules/services/hpos-admin.nix
- modules/services/hpos-init.nix
- modules/services/lair-keystore.nix
- overlays/holo-nixpkgs/holochain/default.nix
- overlays/holo-nixpkgs/lair-keystore/default.nix
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
- profiles/physical/hpos/holoport-nano/default.nix
This pull request is aiming to create holochain service that:
- starts without errors
- communicates with keystore-lair
> Configure holochain service

- profiles/physical/hpos/holoport-nano/default.nix
Fixes a line in the nano profile that was duplicated during merge of release_01 into master
> Nano hotfix

- modules/default.nix
- modules/services/holochain.nix
- modules/services/self-hosted-happs.nix
- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/self-hosted-happs/default.nix
- profiles/logical/hpos/default.nix
Enables elemental-chat on HPOS
> Enable elemental chat

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/host-console-ui/default.nix
Instead of using buggy npm2nix function I used yarn2nix function that reads from yarn.lock. How simple is that?
> host console ui as derivation

- modules/profiles/hpos-admin-features.nix
- modules/services/hpos-admin-api.nix
- modules/system/holo-nixpkgs/auto-upgrade.nix
- overlays/holo-nixpkgs/hpos-admin-api/default.nix
- overlays/holo-nixpkgs/hpos-admin-api/hpos-admin-api.py
- overlays/holo-nixpkgs/hpos-install/hpos-install.sh
- overlays/holo-nixpkgs/hpos-update/hpos-update.sh
- profiles/logical/self-aware.nix
> Fix admin-api 500 error

- overlays/holo-nixpkgs/hpos-holochain-api/README.md
- overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
- overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
- overlays/holo-nixpkgs/hpos-holochain-api/tests/index.test.js
- tests/hpos-holochain-api/default.nix
**Note: ** This Includes the work in PR 655 and so it's pointed to that branch.
> hpos-holochain-api: update hosted_happs to return number of source_chains

- profiles/logical/hpos/default.nix
Configure holochain with 200ms gossip loop instead of 10
> Add kitsune tuning params

- tests/default.nix
- tests/hpos-admin-api/default.nix
When #655 is merged, this will be rebased and retargeted onto `develop`.
> tests: fix hpos-admin-api test

- README.md
If #678 gets implemented, this documentation needs to be updated too.
> README: add a section on running and writing tests

- profiles/logical/hpos/default.nix
Update DNA/UUID to alpha19-develop and use current staging tuning config Also use test proxy
> EC config for develop

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/holochain/default.nix
- overlays/holo-nixpkgs/holochain/lair-keystore/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
The motivation here is to make it convenient to follow a specific branch
for all packages related to holochain, or specify a custom revision for
holochain.
> holochain: add version groups and meta packages

- overlays/holo-nixpkgs/holochain/default.nix
- overlays/holo-nixpkgs/holochain/lair-keystore/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
Extracted from https://github.com/Holo-Host/holo-nixpkgs/pull/749
> bump holochian and add libiconv dep on darwin

- modules/services/configure-holochain.nix
- modules/services/holo-envoy.nix
- overlays/holo-nixpkgs/configure-holochain/default.nix
- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/hc-state-node/default.nix
- overlays/holo-nixpkgs/holo-envoy/default.nix
- overlays/holo-nixpkgs/holochain/default.nix
- overlays/holo-nixpkgs/holochain/lair-keystore/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
- overlays/holo-nixpkgs/tryorama/default.nix
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/test/default.nix
- tests/default.nix
- tests/hpos-api-tests/holochain-api-test.nix
Update to holochain: f8671b45d34c3d1f38f8c642025cbe28610987b5
> catch-up holochain

- overlays/holo-nixpkgs/holochain/default.nix
- profiles/logical/hpos/default.nix
Also includes holochain with cherry-picked chain re-genesis fix
> [No merge deleted when old dna branch not needed] EC refactor:  UI alpha30, DNA alpha21

- overlays/holo-nixpkgs/configure-holochain/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
- overlays/holo-nixpkgs/hpos-holochain-api/package.json
- overlays/holo-nixpkgs/hpos-holochain-api/src/api.js
- overlays/holo-nixpkgs/hpos-holochain-api/src/const.js
- overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
- overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
- overlays/holo-nixpkgs/hpos-holochain-api/yarn.lock
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
> Dev Uid Override

- jobsets.nix
Quick PR that creates additional channel that our Hydra 19.09 can follow. In an effort to make build infrastructure simple transparent.
> Creates hydra-19.09 channel that oud servers can follow

- overlays/holo-nixpkgs/holochain/default.nix
- overlays/holo-nixpkgs/holochain/lair-keystore/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
Updates to https://github.com/holochain/holochain/commit/358018b1ae3c413bd2b58c0b12752c7b38779c09
> Update holochain [D-01227]

- modules/services/configure-holochain.nix
- modules/services/holo-envoy.nix
- modules/services/holochain.nix
- modules/services/hpos-holochain-api.nix
- modules/services/lair-keystore.nix
- overlays/holo-nixpkgs/holochain/versions.nix
- profiles/logical/hpos/sandbox/default.nix
- tests/default.nix
- tests/systemd-resilience-test/README.md
- tests/systemd-resilience-test/default.nix
- tests/systemd-resilience-test/seed.txt
This PR is aiming to set correct order and properties of hosting-related systemd services on HPOS.
Required steps:
> Reconfigure systemd services

- modules/system/holo-nixpkgs/auto-upgrade.nix
- profiles/logical/holo/hydra/default.nix
- profiles/logical/hpos/default.nix
> auto-upgrade timer: startAt -> OnUnitActiveSec

- modules/services/holochain-proxy.nix
- overlays/holo-nixpkgs/holochain/versions.nix
- overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
- overlays/holo-nixpkgs/tryorama/default.nix
@zippy This uses tip of holochain develop. Please check that this is OK and includes the fix for the LMDB size.
> Use proxy-tx2 in develop

- overlays/holo-nixpkgs/holo-envoy/default.nix
- overlays/holo-nixpkgs/holochain/versions.nix
- overlays/holo-nixpkgs/host-console-ui/default.nix
- overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
- overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml
- overlays/holo-nixpkgs/hpos-holochain-client/hpos-holochain-client.py
- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
Full change log filed separately. Key changes are:
- Updated Holochain that fixes invalid joining code and zome call interruption
- Updated Envoy compatible with new Holochain
- HHA (Core-app) bump for current version of elemental chat
- Working host console UI and stats (Once #794 merged into develop and merged in here)
> Release Candidate: Hosted hApps with Host Console Stats

- modules/services/hp-admin-crypto-server.nix
- modules/services/hpos-admin-api.nix
- modules/services/hpos-holochain-api.nix
- overlays/holo-nixpkgs/hpos-led-manager/src/main.rs
> Tweaks behavior of systemd services

- overlays/holo-nixpkgs/hosted-happ-monitor/package.json
- overlays/holo-nixpkgs/hosted-happ-monitor/src/const.js
- overlays/holo-nixpkgs/hosted-happ-monitor/src/index.js
- overlays/holo-nixpkgs/hosted-happ-monitor/yarn.lock
- overlays/holo-nixpkgs/matching-engine/default.nix
- profiles/logical/holo/match-server/default.nix
Adds:
- auto-update
- Post HDK version of holochain
- Latest HHA and servicelogger
> Update match engine 

- overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
> Auto pilot enable happ suggestion

- overlays/holo-nixpkgs/default.nix
- overlays/holo-nixpkgs/holo-cli/default.nix
- overlays/holo-nixpkgs/holo-cli/holo.sh
- overlays/holo-nixpkgs/hpos-holochain-api/src/index.js
- profiles/logical/hpos/default.nix
New CLI `holo`
```
user@nixos: holo help
usage: holo <OPTIONS>
list-hosted-happs | l: List all the hosted happs registered on HHA
help | h: display all usage options
```
> List happs with all needed details and new holo cli

- profiles/logical/hpos/default.nix
- profiles/logical/hpos/sandbox/default.nix
Question: Are we sure that 0001 is unused?
Also: Should this be onto staging instead?
> Hash bump master

- profiles/logical/hpos/default.nix
> profiles/hpos: enable ssh by default
