.gitignore, Makefile, modules/base.nix, scripts/holochain-activation.sh, scripts/holoport-preflight.sh
Attempt to run a HoloPortOS "Preflight" checklist, to check and repair any issues that have been detected since the last deployment of the `scripts/holoport-preflight.sh` script.
- The testing procedure doesn't seem to provide access to any new binaries provisioned in the nix pkgs stanza of base.nix; eg. `rsync`, `logger`.
- sshd.service and zerotier.service should probably be restarted, so new host keys and ZeroTier identity gets immediately created and used; this doesn't occur on automatic update (because these services are already running).
Also, changes the `systemd-activation` to `holochain-activation`, which gets its functionality from `scripts/holochain-activation.sh`.  Furthermore -- this is changed to a simple "oneshot" systemd service that is invoked by a `requires = ...` …
=> Holoport preflight

modules/base.nix, scripts/holoport-preflight.sh
o Ensure that systemd restarts holoport-preflight.service (and
all services requiredBy it), by making it a "oneshot" service
with RemainAfterExit = "yes".
o Scan the mount points and disk by-id to discover serialized name
=> Convert from using Ethernet MAC to root fs' Disk ID for hardware ident.

modules/base.nix, scripts/holoport-preflight.sh
o Arrange that holoport-preflight is run after local-fs, before network
o Reboot on flush of node SSH Host, ZeroTier and /etc/machine-id, to
get fresh /etc/machine-id (required by systemd)
In order to see this work, you'll need to Add your VagrantBox to the VirtualBox console, and start it up that way to see the console.
If you erase /var/lib/holoport/hardware, and then run `sudo make test` to force a switch to this version of holoportos, you'll see it decide that its running on new hardware, and report (via `wall`) that it's going to reboot, to ensure a unique identity for the node.
So, at long last -- whenever the holoport-preflight.service detects new hardware via root-fs /dev/disk/by-id/, it'll purge all the invalid SSH Host, ZeroTier and /etc/machine-id identities, and force a …
=> Ensure clean start-up, preflight, and unique identity w/reboot if needed

profiles/hydra/master/default.nix
Resolves #105. Once merged, temporary `hydra-aarch64-linux.holo.host` `CNAME` record can be removed.
=> profiles/hydra/master: update minion hostnames

profiles/hydra/private-master/default.nix
Use work done in https://github.com/NixOS/hydra/commit/bd7b6fc4011825c2e54fb2e7691fd87dc5f91969#diff-b53e04f6219c4eda4a86bdedcc118e85 instead of basic authorization for private Hydra instance.
=> profiles/hydra/private-master: private = 1

overlays/holo-nixpkgs/dna-packages/happ-store/default.nix, overlays/holo-nixpkgs/dna-packages/holo-hosting-app/default.nix
Reverts Holo-Host/holo-nixpkgs#147
CI doesn't pass: https://hydra.holo.host/eval/237159
Also see: https://github.com/Holo-Host/holo-nixpkgs/pull/147#pullrequestreview-306139640
cc @samrose @zo-el
=> Revert "happ-store, holo-hosting-app: bump to 0.3.0-alpha1"

overlays/holo-nixpkgs/default.nix, profiles/hydra/master/default.nix
Configure hydra to host hpstatus.holo.host. Needs updating to the right github.com/holo-host/hpstatus revision before merging.
=> Start hosting https://hpstatus.holo.host

COPYING
Much of Holo Nixpkgs is patched Nixpkgs code. Importing Nixpkgs license satisfies MIT notice requirement, while also making upstreaming code legally sound.
=> Import Nixpkgs license

README.md
See #130. Since it was decided that `https://cache.nixos.org/` is to stay, it was updated accordingly in Holo Nixpkgs docs and `https://cache.holo.host` was changed to `https://cache.holo.host/` for consistency.
=> README: update binary caches for consistency with #130

.github/CODEOWNERS, .github/settings.yml
See: https://github.com/probot/settings
Note that this also adds `CODEOWNERS` file with me being a codeowner for `modules/` and `profiles/`. Read more about code owners here: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners
=> .github: set up declarative GitHub repo settings via https://github.com/probot/settings

modules/default.nix, modules/services/hp-admin-crypto-server.nix, overlays/holo-nixpkgs/default.nix, profiles/holoportos/default.nix
Integrates HP Admin crypto server into HoloPortOS. cc @peeech
=> hp-admin-crypto-server: init

modules/services/holo-auth-client.nix
Depends on #208. Makes sure that we derive keystore from seed on every boot.
=> nixos/holo-auth-client: derive keystore on every boot

profiles/holoportos/demo/default.nix
During early Open Alpha, we'll be using `sim2h` to provide DHT communications between nodes.
Default to the public `sim2h` server.
TODO: This resolves the "demo" branch; where else are we incorrectly assuming incorrect DHT configuration, eg. `n3h`?
=> profiles/holoportos/demo: use sim2h for networking

overlays/holo-nixpkgs/default.nix
This will deploy new UI to <https://quickstart.holo.host>. Holo-Host/hpos-state@26164a0f79840abfb696fa5bde41f5389dce6143 is the latest HPOS State `develop`.
=> hpos-state: bump to 26164a0f79840abfb696fa5bde41f5389dce6143

profiles/hydra/master/default.nix
This fixes missing MIME type handling on <https://quickstart.holo.host> page that results in vector images not being displayed.
Before:
```
curl -I 'https://quickstart.holo.host/assets/icons/holo-logo-avatar.svg'
HTTP/2 200 
server: nginx
date: Fri, 13 Dec 2019 03:24:45 GMT
content-type: text/plain
content-length: 4398
last-modified: Thu, 01 Jan 1970 00:00:01 GMT
etag: "56g6n98zankv1zkhk9kc5ssnd5hf2ibv"
accept-ranges: bytes
```
After:
```
curl -I 'https://quickstart.holo.host/assets/icons/holo-logo-avatar.svg'
HTTP/2 200 
server: nginx
date: Fri, 13 Dec 2019 03:27:00 GMT
content-type: image/svg+xml
content-length: 4398
last-modified: Thu, 01 Jan 1970 00:00:01 GMT
etag: "56g6n98zankv1zkhk9kc5ssnd5hf2ibv"
accept-ranges: bytes
```
=> profiles/hydra/master: add missing PNG, SVG MIME types for quickstart

overlays/holo-nixpkgs/default.nix, profiles/holoportos/default.nix
This allows to access HPOS using a new Base36 URL and see HP Admin UI (which requires removing redirect and placing UI into root dir).
=> holo-router-agent: bump, profiles/holoportos: host HP Admin at /

overlays/holo-nixpkgs/default.nix
This updates hpos-state right to `develop` rev right before Holo-Host/hpos-config#25 was merged.
=> hpos-state: bump to 62009eeb1fe9be9bb455d3a763acb31a71cf7679

profiles/router-gateway/default.nix
This allows Holo Router to correctly route ACME challenge so that HPOS can get a Let's Encrypt signed TLS certificate.
=> profiles/router-gateway: fix eval, implement HTTP -> HTTPS redirect

profiles/hardware/virtualbox/default.nix
`hpos-state-derive-keystore` and `holo-router-agent` need at least 3GB RAM to reliably run.
cc @alastairong
=> profiles/hardware/virtualbox: bump default RAM to 3GB

modules/system/holoportos.nix
NixOS/nixpkgs@b08b0bcbbec77046e5a7082177cedc12fbf1dc6c broke the original code, so we're going to go with empty mkOption no-op.
=> modules/system/holoportos: ignore network option

overlays/holo-nixpkgs/dna-packages/default.nix, profiles/holoportos/default.nix, tests/holochain-conductor/default.nix
I think we should change the name to `communities` from `hylo-holo-dnas`
=> profiles/holoportos: add hylo-holo-dnas (Communities) DNA

nixpkgs/ext4-no-resize2fs.diff, nixpkgs/source-original.nix
Reverts Holo-Host/holo-nixpkgs#238. Hydra doesn't start, see https://github.com/NixOS/nixpkgs/issues/72783.
=> Revert "nixpkgs: update to cc6cf0a96a627e678ffc996a8f9d1416200d6c81"

modules/default.nix, modules/services/magic-wormhole-mailbox-server.nix, overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/magic-wormhole-mailbox-server/default.nix
This is a service that can be used to set up a Wormhole relay. This is required to run [HPOS Seed](https://github.com/Holo-Host/hpos-seed) integration tests. Additionally, maybe we should self-host our own, especially given that we are now using a custom Wormhole App ID.
=> magic-wormhole-mailbox-server: init at 0.4.1

overlays/holo-nixpkgs/default.nix
`holo-nixpkgs.path`, makes downstream NixOS tests possible. `holo-nixpkgs-tests` was renamed to try to refine idioms in Holo Nixpkgs and make it easier to reason about.
=> holo-nixpkgs-tests -> holo-nixpkgs.tests, holo-nixpkgs.path: init

jobsets.nix, overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/mk-jobsets/default.nix
Resolves #182. Usage example:
```nix
{ pkgs ? import ./nixpkgs.nix {} }: with pkgs;
mkJobsets {
owner = "Holo-Host";
repo = "hpos-seed";
branches = [ "develop" "master" ];
pullRequests = <hpos-seed-pull-requests>;
}
```
cc @samrose @zo-el
=> mkJobsets: init

overlays/holo-nixpkgs/default.nix
Overall this is based on Nix build compatible Holochain build system that I've authored a while ago. It should prove to be very useful for setting up Hydra-based downstream CI.
Usage example:
```nix
let
overlay = final: _: import ./. { pkgs = final; };
nixpkgs = args: import ./nixpkgs.nix (args // {
overlays = [ overlay ];
});
in
with nixpkgs {};
mkBuildMatrix {
inherit overlay;
platforms = {
aarch64-linux-gnu-native = nixpkgs { system = "aarch64-linux"; };
x86_64-darwin-native = nixpkgs { system = "x86_64-darwin"; };
x86_64-linux-gnu-native = nixpkgs { system = "x86_64-linux"; };
};
}
```
=> mkBuildMatrix: init

overlays/holo-nixpkgs/default.nix
I'm not 100% sure about layout yet (`aggregate` and `platforms.<platform>.<dervation>`), and this is not abstract enough to be applied for repos like `holo-nixpkgs`, but this is momentarily useful for downstream Hydra CI.
=> mkRelease: init

nixpkgs/rust-aarch64-musl-cross.diff, nixpkgs/source.nix
This reapplies 4c2a19f313cd2574f38ae2ea543bc43590619d77.
NixOS 19.09 release doesn't include this patch. We'll only get it once we update to 20.03.
=> nixpkgs: restore rust-aarch64-musl-cross.diff

nixpkgs/src/default.nix
NixOS/nixpkgs-channels@c5d5561f772f9ed9de272e3ccb7426de6e862dd1 is the latest `nixos-19.09` revision.
=> nixkpgs/src: bump to c5d5561f772f9ed9de272e3ccb7426de6e862dd1

profiles/logical/hpos/default.nix, profiles/logical/self-aware.nix
If you examine how https://github.com/Holo-Host/holo-nixpkgs/blob/develop/overlays/holo-nixpkgs/hpos-admin-client/hpos-admin-client.py#L43  
hpos-admin-client works it sends requests to `res = request(ctx, 'PUT', '/v1/config' [...]`
removing the trailing slash:
```
diff --git a/profiles/logical/hpos/default.nix b/profiles/logical/hpos/default.nix
index 99ed2e0..d9f4c0a 100644
--- a/profiles/logical/hpos/default.nix
+++ b/profiles/logical/hpos/default.nix
@@ -108,7 +108,7 @@ in
};
"/api/v1/" = {
-          proxyPass = "http://unix:/run/hpos-admin.sock:/";
+          proxyPass = "http://unix:/run/hpos-admin.sock:";
extraConfig = ''
auth_request /auth/;
'';
```
is the only change needed to be able to pass through requests, which should be formed as seen in the hpos-admin-client example
The …
=> 2020 01 02/hpos admin remove uri

modules/services/holochain-conductor.nix, modules/services/sim2h-server.nix, overlays/holo-nixpkgs/build-dna/default.nix, overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/dna-packages/default.nix, overlays/holo-nixpkgs/holochain-rust/default.nix, profiles/logical/hpos/default.nix, tests/holochain-conductor/default.nix
DNAs and dependent packages updated to holochain-rust 0.0.41-alpha4, via their respective `release-0.0.41-alpha4-holo-nixpkgs` branches.
Run `nix-shell` and `hpos-shell`
=> holochain-rust: bump to v0.0.42-alpha4

README.md
Instructions for changing a HoloPort (or HPOS VM) to track holo-nixpkgs repo's develop (or any other) branch rather than master.
I just put these in the readme, but please consider whether they belong elsewhere.
=> Add nix-channel insturctions to README

tests/default.nix
Disables Holochain conductor test for the time being (it doesn't pass after the most recent Holochain bump and thus breaks CI on all PRs).
=> holo-nixpkgs-tests.holochain-conductor: disable

overlays/holo-nixpkgs/dna-packages/default.nix, profiles/logical/hpos/default.nix
Updated pointers for:
- happ-store
- holo-hosting-app
- servicelogger 
- holofuel
Updated all DNAs to use a default sim2h server for specified DNA.
=> Update DNAs to use sharded sim2h servers

overlays/holo-nixpkgs/default.nix
Currently, `hp-admin-ui` is a stopgap derivation. This PR backports `master` HP Admin version (which diverged from `develop`) back into `develop`.
=> hp-admin-ui: backport upstream derivation

overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/nginx/add-wasm-mime-type.patch
Original `mime.types` file in nginx does not contain an entry for application/wasm. Instead of passing `extraConfig` to nginx.conf I have patched nginx `mime.types` file.
=> Patch nginx to include wasm mime type

profiles/logical/hpos/default.nix
This resolves an issue where each change of DNA in conductor configuration was resulting in corrupted local DHT storage.
=> Add DNA hash to instance storage path

.github/settings.yml
This allows anyone in Central and hAppy teams write and `develop` commit access to this repo.
cc @Holo-Host/central @Holo-Host/happy
=> .github/settings.yml: allow Central and hAppy teams commit access

profiles/logical/hpos/default.nix
I noticed several of the holochain log errors are things we probably don't want to see in journalctl logs (e.g. `Aspect already being held`) so I'm trying `type = "info"` in this PR.
=> Test: limit holochain logging to info without state_dumps

overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/dna-packages/default.nix, overlays/holo-nixpkgs/holochain-rust/default.nix
Bumps version of holochain-rust to v0.0.45-alpha1, also bumps all DNAs to a compatible version
=> holochain-rust: version bump to v0.0.45-alpha1

profiles/logical/hpos/staged/default.nix
Enables ssh daemon. That way Hosts can elect to grant access to their HoloPorts to the holders of ssh keys listed in `holo-nixpkgs/profiles/logical/hpos/staged`, by simply updating the config file `/etc/nixos/configuration.nix` on their machine in the following way:
```
{
imports = [
<holo-nixpkgs/profiles/targets/holoport-plus>
+    <holo-nixpkgs/profiles/logical/hpos/staged>
./hardware-configuration.nix
];
...
}
```
Closes #404
=> add staging profile with ssh access open

modules/services/holochain-conductor.nix
Checking if the holochain-conductor state file exists on service start, so we do not overwrite it on each start, given the conductor writes to it. ```hpos-reset``` will take care of removing it if needed.
=> services.holochain-conductor: make conductor config permanent

modules/services/holochain-conductor.nix
Fixes an issue where holochain keystore is not created on conductor start-up
=> Create keystore unconditionally

overlays/holo-nixpkgs/dna-packages/default.nix, profiles/logical/hpos/default.nix
Adds HPOS configuration that imports and installs hosted DNAs, with hosted-holofuel as an example.
=> holochain-conductor: add hostedDnas

profiles/logical/binary-cache.nix, profiles/logical/holo/hydra/master/default.nix, profiles/logical/holo/hydra/minion/default.nix
- Add cache.holo.host-2 to binaryCachePublicKeys 
- `cache.holo.host-1` is deprecated (e.g. private key won't ever be used again).
- `cache.holo.host-2` is the new key (on Hydra), with which all new builds will be signed.
=> Fix Hydra setup

README.md, modules/default.nix, modules/services/automount.nix, modules/system/holo-nixpkgs/usb-reset.nix, overlays/holo-nixpkgs/default.nix, profiles/logical/hpos/default.nix, profiles/logical/hpos/sandbox/default.nix, profiles/physical/hpos/automount.nix, profiles/physical/hpos/holoport-nano/default.nix, profiles/physical/hpos/holoport-plus/default.nix, profiles/physical/hpos/holoport/default.nix
Close #188.
`services.devmon.enable` is defined by [profiles/physical/hpos/automount.nix](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/physical/hpos/automount.nix#L6). If it's enabled, we add an argument `--exec-on-drive` to `ExecStart` (see [`devmon --help`](https://igurublog.wordpress.com/downloads/script-devmon/)).
This executes the script on the mountpoint after `devmon` has finished mounting the drive. This ensures proper unmounting/etc.
=> usb-reset: implement via devmon

profiles/logical/binary-cache.nix
Backport of new public key from #448 to `master`.
=> [backport] Add cache.holo.host-2 to binaryCachePublicKeys

profiles/logical/binary-cache.nix
cache.holo.host-1 is deprecated (e.g. private key won't ever be used again).
cache.holo.host-2 is the new key (on Hydra), with which all new builds will be signed.
Cherry-pick of #454 on `staging`.
=> [staging] Add cache.holo.host-2 to binaryCachePublicKeys

modules/services/holochain-conductor.nix, profiles/logical/hpos/development/default.nix
- Add `$HPOS_DEVELOPMENT_MODE` to global environment
- Check this variable in `preStart` of `holochain-conductor.service`
=> profiles/hpos/development: create

profiles/logical/hpos/default.nix
Adds fields for:
- title
- publisher
- publish date
- release version
To hosted hApps in conductor-config.toml so that HP admin can access them
These fields are supposed to be arbitrary strings with no function
=> profiles/hpos: add descriptive fields

overlays/holo-nixpkgs/hpos-admin-client/hpos-admin-client.py, overlays/holo-nixpkgs/hpos-admin/default.nix, overlays/holo-nixpkgs/hpos-admin/hpos-admin.py
To call `hpos-reset` via HP Admin. Currently not passing tests
=> Add endpoint to trigger a factory reset via HP admin API

overlays/holo-nixpkgs/hpos-admin-client/hpos-admin-client.py, overlays/holo-nixpkgs/hpos-admin/hpos-admin.py, tests/hpos-admin/conductor-config.toml, tests/hpos-admin/default.nix
Updates the `/hosted_happs` endpoint to also provide the number of hosted instances for each hosted_happ ID.
=> HP Admin return number of hosted instances per happ

tests/default.nix, tests/hpos-admin/default.nix
The current tests for hpos-admin were depended on the hash of the holofuel DNA. 
This DNA keeps changing and so we would have to update the tests every-time we update the hash-space.
This PR checks all the necessary details that need to be returned by the `get-hosted-happs` endpoint and avoids looking for the DNA hash
=> tests/hpos-admin: update tests to not dependent on holofuel dna-hash

overlays/holo-nixpkgs/hpos-update/hpos-update.sh
1) Confirmed that this "does no harm" - `hpos-update` works as usual in the success case
2) Confirmed that this fixes standard errors leading to false positive. When update fails, `get-status` will show the correct (pre-update) holo-nixpkgs hash
3) Confirmed that script captures the correct output to `grep` for cached results
4) CAN NOT reproduce actual cached result error
=> HPOS update handles cache result scenario

overlays/holo-nixpkgs/hpos-init/hpos_init/main.py
Customer mrcat in China reports that their HoloPort cannot connect to our network. Screenshot suggests this is due to an unhandled error with Wormhole, which is a currently unused service set up for future VMs and Cloudports.
This is a basic error handler to address the issue for HP owners - we will probably need something more robust when Cloudports are operating.
Note that this nixOS project also had a very similar / the same issue and it may be caused with an unhandled error in the Twisted library.
https://github.com/Tribler/tribler/issues/3440#issuecomment-400987017
=> Add wormhole error handling to fix customer bug

profiles/logical/hpos/default.nix
This should fix `gtk+` -> `cairo` builds.
=> profiles/hpos: set noXlibs = false

nixpkgs/src/default.nix, overlays/holo-nixpkgs/hpos-update/hpos-update.sh
- Add verbose flag to hpos-update
- Bump for upstream lv2m bug fix (causes confusing false error messages)
=> Rc2 hotfixes

overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/hc-state-node/default.nix, profiles/logical/hpos/default.nix
Adds `hc-state` CLI to HPOS (type `hc-state` for more info)
=> treewide: add hc-state command to HPOS

overlays/holo-nixpkgs/hc-state-node/default.nix, overlays/holo-nixpkgs/holochain/default.nix, overlays/holo-nixpkgs/hpos-holochain-api/package-lock.json, overlays/holo-nixpkgs/hpos-holochain-api/package.json, overlays/holo-nixpkgs/hpos-holochain-api/src/index.js, overlays/holo-nixpkgs/lair-keystore/default.nix, overlays/holo-nixpkgs/self-hosted-happs/default.nix, profiles/logical/hpos/default.nix
- bumps holochain and all its dependencies
- currently failing to build are holochain and lair. see: 47d973ec3d394cf11f71e603eb42ac162e350af3
=> elemental-chat fixes by bumping holochain

overlays/holo-nixpkgs/default.nix, profiles/physical/hpos/holoport-nano/default.nix
Currently nano is set to follow latest kernel. This was done back when old kernel (v5.1) did not have good support for Allwinner A64. Current LTS 5.4 which x64 HoloPorts follow has good support.
This fixes #628
=> Switch nano kernel version to follow default NixOS version

profiles/logical/holo/hydra/master/specs/holo-envoy.json
Too frequent checks for changes are triggering a flood of evaluations on server. This is consuming significant amount of CPU. I am switching from 10s interval to 60s interval.
=> checkinterval from 10s -> 60s

overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/holochain/default.nix
This change makes holo-nixpkgs viable to be used by holonix and potentially other consumers as a source for the holochain packages.
Changes made
=> [TK-06431] Build holochain without default features and bump Rust to 1.48.0; bump Holochain; expose Rust and Holochain expressions

overlays/holo-nixpkgs/configure-holochain/default.nix, overlays/holo-nixpkgs/holochain/default.nix, profiles/logical/hpos/default.nix
- bumps holochain to latest version (includes gossip fixes and RegisterDna updates)
- uses hpos-configure-holochain with UUID
- uses elemental chat ui alpha20
- sets uuid for elemental chat so we have a different hash-space
=> DevTest: EC and configure-holochain updates

overlays/holo-nixpkgs/default.nix
@peeech Moving disable VM to a separate PR so we can merge it in faster and keep PRs small
=> overlays: disable virtualbox VM build

overlays/holo-nixpkgs/hpos-admin-api/README.md
The API endpoint documentation belongs here, not in a separate rfcs repo!
Also updated it to reflect the actual endpoints
=> hpos-admin-api: add api usage documentation

modules/services/holochain.nix, profiles/logical/hpos/default.nix
Adds a 2 hour restart timer to holochain service, as a hacky stop gap to networking performance degradation.
Note: we will need to reduce this frequency with hosted happs due poor UX.
=> Holochain restart timer hot fix

overlays/holo-nixpkgs/hpos-install/default.nix
Manufactured HP Pluses have OS installed on sdb
=> overlays/hpos-install: change holoport+ disk target from sda to sdb

README.md, overlays/holo-nixpkgs/default.nix, shell.nix
Mostly for tests (`hpos-shell test` will start a VM against test machine profile).
Requires Oleksi's work on test profiles to be merged.
=> Add ability to run `hpos-shell` against selected hpos profile

profiles/logical/hpos/default.nix
Without this, when you are logged into host console and refresh the page you get a `404` error.
With this, you get re-directed to login again.
This follows this pattern:
https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations
Note at the bottom of the link it recommends setting a 404 redirect within the Vue Router itself, which I have not done (I tried but I got some weird `"*" invalid route` errors and it didn't seem worth the effort to debug.
=> Add tryFiles to nginx host console config to prevent refresh errors

modules/services/hpos-led-manager.nix, overlays/holo-nixpkgs/hpos-led-manager/src/main.rs, profiles/logical/hpos/default.nix
If LED manager cannot make a proxy-cli call to the proxy server, it will start flashing orange
I tested this by giving it a fake proxy address and it seems to work fine.
=> Add a flashing orange state to highlight holochain connectivity issues

release.nix
Use attrNames for constituents instead of attrValues. Fixes #746.
cc @grahamc
=> release.nix: fix Hydra evaluations with remote builders

overlays/holo-nixpkgs/hpos-holochain-api/.gitignore, overlays/holo-nixpkgs/hpos-holochain-api/README.md, overlays/holo-nixpkgs/hpos-holochain-api/package.json, overlays/holo-nixpkgs/hpos-holochain-api/scripts/fetch-dna.sh, overlays/holo-nixpkgs/hpos-holochain-api/scripts/setup-holochain.js, overlays/holo-nixpkgs/hpos-holochain-api/src/api.js, overlays/holo-nixpkgs/hpos-holochain-api/src/const.js, overlays/holo-nixpkgs/hpos-holochain-api/src/index.js, overlays/holo-nixpkgs/hpos-holochain-api/tests/config.yaml, overlays/holo-nixpkgs/hpos-holochain-api/tests/index.test.js, overlays/holo-nixpkgs/hpos-holochain-api/yarn.lock, overlays/holo-nixpkgs/hpos-holochain-client/hpos-holochain-client.py
Changes:
- Update to use `@holochain/conductor-api@0.1.0`
- Update to use `bundle_url` provided by HHA for installing hosted happs, rather than using each `dna_url` individually.
- Update to use `hc sandbox` instead of `holochain-run-dna`
- Update the versions of servicelogger and HHA that get downloaded for testing
- Fix pre-existing apparent bug where we don't reliably wait for input to come through when handling an HTTP request (Hasn't seemed to show up in practice though)
I did not end up changing the servicelogger cloning mechanism. I tried using the newly introduced `createCloneCell` but it only allows you to clone cells such that they end up inside of an already active app. In the future it might make sense to move all of the servicelogger instances into one app, and use `slotId`s …
=> overlays/holo-nixpkgs/hpos-holochain-api: Catch up to new holochain

overlays/holo-nixpkgs/hpos-holochain-api/src/index.js, overlays/holo-nixpkgs/hpos-holochain-client/hpos-holochain-client.py
This fixes a regression in `hpos-holochain-api` that was trying to read the body of `GET /hosted_happs` rather than getting the args from the query string.
It also fixes a bug in `hpos-holochain-client` where we were not properly passing the args in the query string.
=> D-012420 fix regression and hpos-holochain-client bug

modules/services/holo-envoy.nix, overlays/holo-nixpkgs/holo-envoy/default.nix, overlays/holo-nixpkgs/holochain/versions.nix, profiles/logical/hpos/default.nix
Includes
- Holochain tip of `sync-genesis` branch (`1050f6b`)
- Holo-Envoy tip of PR 124
- HHA v0.1.0-alpha10 (points to elemental chat v0.2.0-alpha7)
=> Resilient Hosted Happs

overlays/holo-nixpkgs/holo-router/default.nix
Bumps router-gateway to rev with adjusted logging for easier debugging of holo network
=> overlays/holo-router: bump to 9d99427a

overlays/holo-nixpkgs/holo-router/default.nix
Bumps router-gateway to rev with adjusted logging for easier debugging of holo network. This change has been extensively tested on develop and works great.
=> Bump router-gateway

overlays/holo-nixpkgs/configure-holochain/default.nix, overlays/holo-nixpkgs/default.nix, overlays/holo-nixpkgs/holo-auto-installer/default.nix, overlays/holo-nixpkgs/holochain/versions.nix, profiles/logical/hpos/default.nix, profiles/logical/hpos/sandbox/default.nix
Prepare holo-nixpkgs for the next round of testing.
=> Bump holochain that uses wasmer updates

profiles/logical/hpos/default.nix
This PR enables SSH by default so that we can better support our users. 
We will separately add in functionality so that disabling SSH via UI takes precedent over this.
=> profiles/hpos: enable SSH by default

profiles/logical/hpos/default.nix
Adding a mkForce in case users have conflicting ssh declarations in their local `configuration.nix`, which can happen due to customer support guidance
=> Force enable SSH in master
